#!/usr/bin/env python3
"""Generate src/unicode_tables.zig from the Unicode Character Database.

    UCD=17.0.0; mkdir -p /tmp/ucd && cd /tmp/ucd
    for f in UnicodeData.txt SpecialCasing.txt DerivedCoreProperties.txt \
             auxiliary/GraphemeBreakProperty.txt auxiliary/GraphemeBreakTest.txt \
             emoji/emoji-data.txt; do
      curl -sfSLO https://www.unicode.org/Public/$UCD/ucd/$f
    done
    python3 tools/gen_unicode_tables.py /tmp/ucd > src/unicode_tables.zig
    cp /tmp/ucd/GraphemeBreakTest.txt src/testdata/GraphemeBreakTest.txt

The version is read from the header of GraphemeBreakProperty.txt and must
match every other file's, or this stops. Pick the version the comparison
target uses: `elixir -e 'IO.inspect String.Unicode.version()'` (17.0.0 for
Elixir 1.19).
"""
import os
import re
import sys

ucd = sys.argv[1]


def path(name):
    return os.path.join(ucd, name)


def version_of(name):
    with open(path(name), encoding="utf-8") as f:
        head = f.readline()
    m = re.search(r"-(\d+\.\d+\.\d+)\.txt", head)
    return m.group(1) if m else None


version = version_of("GraphemeBreakProperty.txt")
for other in ("DerivedCoreProperties.txt", "SpecialCasing.txt", "GraphemeBreakTest.txt"):
    v = version_of(other)
    if v != version:
        sys.exit(f"{other} is Unicode {v}, GraphemeBreakProperty.txt is {version}")


def ranges(name, want_field=None):
    """Yield (lo, hi, value) from a `lo..hi ; value # ...` property file."""
    with open(path(name), encoding="utf-8") as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            fields = [x.strip() for x in line.split(";")]
            cps = fields[0]
            if ".." in cps:
                lo, hi = (int(x, 16) for x in cps.split(".."))
            else:
                lo = hi = int(cps, 16)
            yield lo, hi, fields[1:]


def merge(rs):
    rs = sorted(rs)
    out = []
    for lo, hi, v in rs:
        if out and out[-1][2] == v and out[-1][1] + 1 == lo:
            out[-1] = (out[-1][0], hi, v)
        else:
            if out and lo <= out[-1][1]:
                sys.exit(f"overlapping ranges at {lo:04X}")
            out.append((lo, hi, v))
    return out


GCB = {
    "CR": "cr", "LF": "lf", "Control": "control", "Extend": "extend",
    "ZWJ": "zwj", "Regional_Indicator": "regional_indicator",
    "Prepend": "prepend", "SpacingMark": "spacing_mark",
    "L": "l", "V": "v", "T": "t", "LV": "lv", "LVT": "lvt",
}
gcb = merge((lo, hi, GCB[f[0]]) for lo, hi, f in ranges("GraphemeBreakProperty.txt"))

ext_pict = merge(
    (lo, hi, True) for lo, hi, f in ranges("emoji-data.txt") if f[0] == "Extended_Pictographic"
)

INCB = {"Linker": "linker", "Consonant": "consonant", "Extend": "extend"}
incb = merge(
    (lo, hi, INCB[f[1]])
    for lo, hi, f in ranges("DerivedCoreProperties.txt")
    if f[0] == "InCB"
)

# Simple case mappings: UnicodeData.txt fields 12 (upper) and 13 (lower).
upper, lower = {}, {}
with open(path("UnicodeData.txt"), encoding="utf-8") as f:
    for line in f:
        fields = line.rstrip("\n").split(";")
        cp = int(fields[0], 16)
        if fields[12]:
            upper[cp] = int(fields[12], 16)
        if fields[13]:
            lower[cp] = int(fields[13], 16)

# Full mappings: the unconditional lines of SpecialCasing.txt. A line with a
# fifth field is conditional (Final_Sigma, or a language: lt, tr, az) and is
# skipped -- Elixir's default mode skips them too.
special_upper, special_lower = {}, {}
with open(path("SpecialCasing.txt"), encoding="utf-8") as f:
    for line in f:
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        fields = [x.strip() for x in line.split(";")]
        if len(fields) > 5 and fields[4]:
            continue
        cp = int(fields[0], 16)
        lo = [int(x, 16) for x in fields[1].split()]
        up = [int(x, 16) for x in fields[3].split()]
        if lo != [cp] and len(lo) != 1:
            special_lower[cp] = lo
        elif lo != [cp] and lower.get(cp) != lo[0]:
            sys.exit(f"SpecialCasing lower for {cp:04X} disagrees with UnicodeData")
        if up != [cp] and len(up) != 1:
            special_upper[cp] = up
        elif up != [cp] and upper.get(cp) != up[0]:
            sys.exit(f"SpecialCasing upper for {cp:04X} disagrees with UnicodeData")

for table in (special_lower, special_upper):
    for cp, seq in table.items():
        if len(seq) > 3:
            sys.exit(f"{cp:04X} maps to {len(seq)} code points; the table holds 3")

w = sys.stdout.write
w(f"// Generated by tools/gen_unicode_tables.py from the Unicode {version} UCD.\n")
w("// Do not edit; regenerate. See the script for the commands.\n\n")
w(f'pub const unicode_version = "{version}";\n\n')
w("pub const Gcb = enum(u8) { other, cr, lf, control, extend, zwj, regional_indicator, prepend, spacing_mark, l, v, t, lv, lvt };\n")
w("pub const InCB = enum(u8) { none, linker, consonant, extend };\n")
w("pub const GcbRange = struct { lo: u21, hi: u21, p: Gcb };\n")
w("pub const InCBRange = struct { lo: u21, hi: u21, p: InCB };\n")
w("pub const Range = struct { lo: u21, hi: u21 };\n")
w("pub const Map = struct { from: u21, to: u21 };\n")
w("/// `to[0..len]` is the mapping.\n")
w("pub const Multi = struct { from: u21, to: [3]u21, len: u2 };\n\n")


def emit_ranges(name, typ, rs, with_value):
    w(f"// {len(rs)} ranges\n")
    w(f"pub const {name} = [_]{typ}{{\n")
    for lo, hi, v in rs:
        if with_value:
            w(f"    .{{ .lo = 0x{lo:X}, .hi = 0x{hi:X}, .p = .{v} }},\n")
        else:
            w(f"    .{{ .lo = 0x{lo:X}, .hi = 0x{hi:X} }},\n")
    w("};\n\n")


def emit_map(name, m):
    w(f"// {len(m)} mappings\n")
    w(f"pub const {name} = [_]Map{{\n")
    for k in sorted(m):
        w(f"    .{{ .from = 0x{k:X}, .to = 0x{m[k]:X} }},\n")
    w("};\n\n")


def emit_multi(name, m):
    w(f"// {len(m)} mappings\n")
    w(f"pub const {name} = [_]Multi{{\n")
    for k in sorted(m):
        seq = m[k] + [0] * (3 - len(m[k]))
        body = ", ".join(f"0x{x:X}" for x in seq)
        w(f"    .{{ .from = 0x{k:X}, .to = .{{ {body} }}, .len = {len(m[k])} }},\n")
    w("};\n\n")


emit_ranges("gcb_ranges", "GcbRange", gcb, True)
emit_ranges("ext_pict_ranges", "Range", ext_pict, False)
emit_ranges("incb_ranges", "InCBRange", incb, True)
emit_map("lower_simple", lower)
emit_map("upper_simple", upper)
emit_multi("lower_full", special_lower)
emit_multi("upper_full", special_upper)
